variables: &global-variables
  COVERAGE_RCFILE: .coveragerc
  DOCKER_BUILDKIT: 1
  GIT_DEPTH: 10
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"

stages:
  - build_image
  - build
  - test
  - test_coverage
  - upload


.job_template: &setup
  image: &dev_image $CI_REGISTRY_IMAGE/build:latest
  before_script:
    - g++ --version
    - python3 --version
  except:
    - schedules


.test_template: &py_setup
  image: &dev_image $CI_REGISTRY_IMAGE/build:latest
  stage: test
  before_script:
    - g++ --version
    - python3 --version
    - pip3 install $(echo dist/*.whl)
  except:
    - schedules
  artifacts:
    paths:
      - .coverage.*
      - "*.xml"
    reports:
      junit:
        - "*.xml"
  interruptible: true


.docker_build_base: &docker_build
  image: docker:latest
  stage: build_image
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/build:latest || true
    - docker build --pull=true --cache-from $CI_REGISTRY_IMAGE/build:latest -t $CI_REGISTRY_IMAGE/build:latest .
    - docker push $CI_REGISTRY_IMAGE/build:latest

docker_build_schedule:
  <<: *docker_build
  only:
    - schedules

docker_build_manual:
  <<: *docker_build
  when: manual
  except:
    - schedules

wheel_build:
  <<: *setup
  stage: build
  script:
    - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl

PBP:
  <<: *py_setup
  script:
    - coverage run -m xmlrunner test/test_pbp.py

Issue:
  <<: *py_setup
  script:
    - coverage run -m xmlrunner test/test_issue.py

coverage:
  <<: *setup
  stage: test_coverage
  script:
    - mkdir -p public/coverage
    - coverage combine
    - coverage report
    - coverage html -d public/coverage
  artifacts:
    paths:
      - public/coverage
  coverage: '/^TOTAL.*\s+(\d+\%)$/'


README_MD:
  image: iquiw/alpine-emacs
  stage: build
  script:
    - emacs --batch README.org --eval '(org-md-export-to-markdown)'
  artifacts:
    paths:
      - README.md
  except:
    - schedules

pypi:
  image: *dev_image
  stage: upload
  environment: production
  script:
    - rm -rf dist
    - python3 setup.py clean
    - python3 setup.py sdist bdist_wheel
    - twine upload --verbose dist/b4tf-*
  only:
    - tags
  except:
    - branches
    - schedules
  needs:
    - README_MD
    - coverage
