baseURL = "https://ymd_h.gitlab.io/b4tf/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Bayes Neural Net for TensorFlow"
theme = "learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
publishDir = "../public"

[params]
  editURL = ""
  description = "Site for b4tf (Bayes Neural Net for TensorFlow)"
  author = "Hiroyuki Yamada"
  showVisitedLinks = false
  disableBreadcrumb = true
  disableNextPrev = true
  themeVariant = "b4tf"
  disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-gitlab'></i> Gitlab"
identifier = "ds"
url = "https://gitlab.com/ymd_h/b4tf"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Class Reference"
identifier = "api"
url = "https://ymd_h.gitlab.io/b4tf/api/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bug'></i> Unit Test Coverage"
identifier = "cov"
url = "https://ymd_h.gitlab.io/b4tf/coverage/"
weight = 30


[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-blog'></i> Author's Blog"
identifier = "blg"
url = "https://ymd_h.gitlab.io/ymd_blog/"
weight = 40
